import { request, ApiError } from "./http.js";

// Fetch a page of products. Pass the previous page's `next_cursor` to get the next one.
export function fetchProducts({ limit = 12, cursor, includeInactive = false, idToken } = {}) {
  const params = new URLSearchParams({ limit: String(limit) });
  if (cursor) params.set("cursor", cursor);
  if (includeInactive) params.set("include_inactive", "true");
  return request(`/api/v1/products?${params.toString()}`, { idToken });
}

export function fetchProductById(id, idToken) {
  return request(`/api/v1/products/${encodeURIComponent(id)}`, { idToken });
}

export function fetchAdminProducts({ limit = 100, cursor, idToken } = {}) {
  const params = new URLSearchParams({ limit: String(limit) });
  if (cursor) params.set("cursor", cursor);
  return request(`/api/v1/products/admin?${params.toString()}`, { idToken });
}

export function createProduct(product, idToken) {
  return request("/api/v1/products", { method: "POST", body: product, idToken });
}

export function updateProduct(id, product, idToken) {
  return request(`/api/v1/products/${encodeURIComponent(id)}`, {
    method: "PUT", body: product, idToken,
  });
}

export function setProductActive(id, active, idToken) {
  return request(`/api/v1/products/${encodeURIComponent(id)}/${active ? "activate" : "deactivate"}`, {
    method: "PATCH", idToken,
  });
}

// The presigned URL is generated by product-service (admin-only), but the
// actual upload goes straight from the browser to S3 — request()'s wrapper
// always JSON-encodes and sets Content-Type: application/json, which is
// wrong for a raw file PUT, so this uses fetch() directly for that step.
export async function requestImageUploadUrl(contentType, idToken) {
  return request("/api/v1/products/admin/image-upload-url", {
    method: "POST",
    body: { content_type: contentType },
    idToken,
  });
}

export async function uploadProductImage(file, idToken) {
  const { post_url, fields, image_url } = await requestImageUploadUrl(file.type, idToken);

  // S3's presigned-POST form: every signed field first, "file" last — S3
  // ignores any form field that appears after it. The browser sets its own
  // multipart Content-Type (with boundary) for a FormData body; setting one
  // by hand here would break the signature.
  const formData = new FormData();
  for (const [key, value] of Object.entries(fields)) formData.append(key, value);
  formData.append("file", file);

  let response;
  try {
    response = await fetch(post_url, { method: "POST", body: formData });
  } catch {
    throw new ApiError("Could not upload the image. Please try again.", 0);
  }
  if (!response.ok) {
    // S3 returns an XML error body (e.g. EntityTooLarge past the signed
    // content-length-range) rather than JSON — not worth parsing for a
    // message the 5MB client-side check should already have caught.
    throw new ApiError("Could not upload the image. Please try again.", response.status);
  }

  return image_url;
}
